"""empty message

Revision ID: 340b94ca76b7
Revises: 
Create Date: 2020-08-22 06:10:58.131823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340b94ca76b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=24), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=True),
    sa.Column('nome', sa.Unicode(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
