"""empty message

Revision ID: 5fa381f95cf1
Revises: 
Create Date: 2020-08-22 19:47:23.564069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa381f95cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preVagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('tel', sa.Unicode(), nullable=False),
    sa.Column('nome', sa.Unicode(), nullable=False),
    sa.Column('email', sa.Unicode(), nullable=False),
    sa.Column('cidade', sa.Unicode(), nullable=False),
    sa.Column('estado', sa.Unicode(), nullable=False),
    sa.Column('empresa', sa.Unicode(), nullable=False),
    sa.Column('salario', sa.Unicode(), nullable=False),
    sa.Column('categoria', sa.String(length=128), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=False),
    sa.Column('disponivel', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=24), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=True),
    sa.Column('nome', sa.Unicode(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Unicode(), nullable=False),
    sa.Column('email', sa.Unicode(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.Unicode(), nullable=False),
    sa.Column('salario', sa.Unicode(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=False),
    sa.Column('disponivel', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vagas')
    op.drop_table('usuario')
    op.drop_table('preVagas')
    # ### end Alembic commands ###
